service: lambda-sls-esbuild-init

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  memorySize: 512
  timeout: 120
  region: eu-west-2 # AWS region
  deploymentMethod: direct
  deploymentBucket:
    name: lambda-eu-west-2-deploys

package:
  patterns:
    - "!**/*.test.ts"

functions:
  example:
    handler: src/example/index.handler

plugins:
  - serverless-esbuild
